version: '3'
services:
  fast_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SYNC_CONFIG_FILE_PATH: ${SYNC_CONFIG_FILE_PATH}
    volumes:
      - ${WG_CONFIG_PATH}:${WG_CONFIG_PATH}
      - ${SOURCE_SYNC_CONFIG_FILE_PATH}:${SYNC_CONFIG_FILE_PATH}
    env_file:
      - .env
    network_mode: "host"
    privileged: true
    command: uvicorn api.main:app --host 0.0.0.0 --port ${FAST_API_PORT}
    ports:
      - "${FAST_API_PORT}:${FAST_API_PORT}"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
